# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '9.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(432, 412)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 431, 211))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.checkBox = QtGui.QCheckBox(self.tab)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(252, 27, 161, 22))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(16, 133, 374, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(85, 27, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.spinBox = QtGui.QSpinBox(self.tab)
        self.spinBox.setGeometry(QtCore.QRect(20, 20, 51, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(3)
        self.spinBox.setProperty("value", 2)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 76, 254, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(323, 76, 38, 30))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(241, 33, 125, 30))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(59, 33, 51, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(109, 33, 126, 30))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(59, 73, 51, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(239, 13, 103, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(109, 73, 126, 30))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(241, 73, 125, 30))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(139, 13, 66, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(16, 133, 251, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 133, 100, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.checkBox_3 = QtGui.QCheckBox(self.tab_4)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 20, 210, 22))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.comboBox_2 = QtGui.QComboBox(self.tab_4)
        self.comboBox_2.setEnabled(True)
        self.comboBox_2.setGeometry(QtCore.QRect(300, 16, 60, 27))
        self.comboBox_2.setAutoFillBackground(False)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.label_14 = QtGui.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(280, 16, 21, 30))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.comboBox = QtGui.QComboBox(self.tab_4)
        self.comboBox.setGeometry(QtCore.QRect(300, 68, 90, 27))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_13 = QtGui.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(304, 45, 81, 31))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.checkBox_4 = QtGui.QCheckBox(self.tab_4)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 68, 210, 22))
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(45, 84, 131, 31))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(45, 120, 130, 30))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.comboBox_3 = QtGui.QComboBox(self.tab_4)
        self.comboBox_3.setEnabled(True)
        self.comboBox_3.setGeometry(QtCore.QRect(300, 120, 80, 27))
        self.comboBox_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.comboBox_3.setAutoFillBackground(False)
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.lineEdit = QtGui.QLineEdit(self.tab_3)
        self.lineEdit.setGeometry(QtCore.QRect(254, 6, 110, 30))
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(44, 4, 148, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.checkBox_2 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 140, 186, 22))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(254, 48, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(44, 34, 157, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(44, 54, 157, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(44, 84, 187, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(254, 94, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.label_12 = QtGui.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(44, 104, 187, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(241, 380, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.textBrowser = QtGui.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(6, 256, 420, 120))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(6, 219, 420, 27))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(7, 386, 234, 16))
        self.line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(5, 395, 130, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(4)
        self.comboBox_3.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "FortyFour", None))
        self.checkBox.setText(_translate("Dialog", "Zobrazovat grafy", None))
        self.pushButton.setText(_translate("Dialog", "Vybrat složku se soubory FRK", None))
        self.label_10.setText(_translate("Dialog", "Typ výpočtu pozadí", None))
        self.label_8.setText(_translate("Dialog", "Počet cyklů při vyhlazování pozadí:", None))
        self.lineEdit_2.setText(_translate("Dialog", "8", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Hlavní okno", None))
        self.lineEdit_5.setText(_translate("Dialog", "510.9989", None))
        self.label_3.setText(_translate("Dialog", "1. bod", None))
        self.lineEdit_3.setText(_translate("Dialog", "1085.7", None))
        self.label_4.setText(_translate("Dialog", "2. bod", None))
        self.label_2.setText(_translate("Dialog", "Energie (keV)", None))
        self.lineEdit_4.setText(_translate("Dialog", "2783.6", None))
        self.lineEdit_6.setText(_translate("Dialog", "1460.83", None))
        self.label.setText(_translate("Dialog", "Kanál", None))
        self.pushButton_2.setText(_translate("Dialog", "Vybrat konfigurační soubor", None))
        self.pushButton_3.setText(_translate("Dialog", "Uložit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Energetická kalibrace", None))
        self.checkBox_3.setText(_translate("Dialog", "Vícevláknové zpracování", None))
        self.comboBox_2.setItemText(0, _translate("Dialog", "2", None))
        self.comboBox_2.setItemText(1, _translate("Dialog", "4", None))
        self.comboBox_2.setItemText(2, _translate("Dialog", "8", None))
        self.comboBox_2.setItemText(3, _translate("Dialog", "16", None))
        self.comboBox_2.setItemText(4, _translate("Dialog", "CPU", None))
        self.comboBox_2.setItemText(5, _translate("Dialog", "MAX", None))
        self.label_14.setText(_translate("Dialog", "#:", None))
        self.comboBox.setItemText(0, _translate("Dialog", "Energie", None))
        self.comboBox.setItemText(1, _translate("Dialog", "Plocha", None))
        self.comboBox.setItemText(2, _translate("Dialog", "Reakce", None))
        self.comboBox.setItemText(3, _translate("Dialog", "Intensita", None))
        self.comboBox.setItemText(4, _translate("Dialog", "Isotop", None))
        self.comboBox.setItemText(5, _translate("Dialog", "Poločas", None))
        self.label_13.setText(_translate("Dialog", "Řadit dle:", None))
        self.checkBox_4.setText(_translate("Dialog", "Vyhodnocovat spektrum", None))
        self.label_15.setText(_translate("Dialog", "(online databáze)", None))
        self.label_16.setText(_translate("Dialog", "Počet kanálů:", None))
        self.comboBox_3.setItemText(0, _translate("Dialog", "1024", None))
        self.comboBox_3.setItemText(1, _translate("Dialog", "2048", None))
        self.comboBox_3.setItemText(2, _translate("Dialog", "4096", None))
        self.comboBox_3.setItemText(3, _translate("Dialog", "8192", None))
        self.comboBox_3.setItemText(4, _translate("Dialog", "16384", None))
        self.comboBox_3.setItemText(5, _translate("Dialog", "32768", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Nastavení", None))
        self.lineEdit.setText(_translate("Dialog", "1", None))
        self.label_5.setText(_translate("Dialog", "Faktor šířky píku", None))
        self.checkBox_2.setText(_translate("Dialog", "Vyhlazovat spektrum", None))
        self.lineEdit_8.setText(_translate("Dialog", "-10000", None))
        self.label_11.setText(_translate("Dialog", "Diskriminace dle", None))
        self.label_7.setText(_translate("Dialog", "amplitudy píku", None))
        self.label_9.setText(_translate("Dialog", "Váha prostřední hodnoty", None))
        self.lineEdit_9.setText(_translate("Dialog", "50", None))
        self.label_12.setText(_translate("Dialog", "při vyhlazování pozadí", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Další nastavení", None))
        self.buttonBox.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_6.setText(_translate("Dialog", "Dominik Thomas OJR ÚJF", None))

